{% set name = "timbertrek" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/timbertrek-{{ version }}.tar.gz
  sha256: 83f558ecfb4d8b11a79525cc7846b185803a707455566e638f15dfd26de3084b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - ipython
    - tqdm

test:
  imports:
    - timbertrek
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/poloclub/timbertrek
  summary: Explore and compare decision trees in a web browser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
